name: 'test for github apps'

on:
  push:
    paths:
    branches:
      - '**'
      - '!main'
jobs:
  job:
    runs-on: ubuntu-latest
    steps:
      - name: Generate token
        id: generate_token
        uses: getsentry/action-github-app-token@v1
        with:
          app_id: ${{ secrets.APPS_ID }}
          private_key: ${{ secrets.APPS_PUBLIC_KEY }}
      - name: Use token
        env:
          TOKEN: ${{ steps.generate_token.outputs.token }}
        run: |
          echo "The generated token is masked: ${TOKEN}"
